// ⚠️  DEPRECATED — Do NOT edit this file.
// This file is kept for backwards compatibility only.
// All endpoints are now defined in:
//   lib/core/constants/api_endpoints.dart
//
// If you are importing this file, please change your import to:
//   import '../../core/constants/api_endpoints.dart';
export '../../core/constants/api_endpoints.dart';
