// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5Y3wqmNHV8D2hvwfojgqW0tswaSNXoY',
    appId: '1:263138873815:web:700ee51291052b9e1dfb92',
    messagingSenderId: '263138873815',
    projectId: 'qr-task-manager-app',
    authDomain: 'qr-task-manager-app.firebaseapp.com',
    storageBucket: 'qr-task-manager-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5Y3wqmNHV8D2hvwfojgqW0tswaSNXoY',
    appId: '1:263138873815:android:manual_android_placeholder',
    messagingSenderId: '263138873815',
    projectId: 'qr-task-manager-app',
    storageBucket: 'qr-task-manager-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5Y3wqmNHV8D2hvwfojgqW0tswaSNXoY',
    appId: '1:263138873815:ios:manual_ios_placeholder',
    messagingSenderId: '263138873815',
    projectId: 'qr-task-manager-app',
    storageBucket: 'qr-task-manager-app.firebasestorage.app',
    iosBundleId: 'com.example.qrTaskApp',
  );
}
